//! The self-describing run artifact (design §3.3): captures +
//! dissectors + visualether.toml + snapshot land together so the
//! VisualEther MCP tools work with no manual setup.

use std::path::Path;

use anyhow::Context as _;
use serde::Serialize;

use crate::config::LoadedScenario;

/// The dissector that exactly matches this build's codecs — both are
/// generated from crates/protocols/pdl/link.pdl at the same commit.
const LINK_LUA: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../protocols/dissectors/link.lua"));

#[derive(Serialize)]
struct Snapshot<'a> {
    helixsim_version: &'a str,
    trace_sha256: &'a std::collections::BTreeMap<String, String>,
    #[serde(flatten)]
    scenario: &'a crate::config::ScenarioFile,
}

pub fn write_static_outputs(run_dir: &Path, loaded: &LoadedScenario) -> anyhow::Result<()> {
    std::fs::create_dir_all(run_dir.join("nodes")).context("create nodes/")?;
    std::fs::create_dir_all(run_dir.join("dissectors")).context("create dissectors/")?;
    std::fs::write(run_dir.join("dissectors").join("link.lua"), LINK_LUA)
        .context("write dissector")?;

    // VisualEther resolves only kerberos.file:/tls.keylog_file: tokens
    // against the toml dir — lua_script: must be absolute (fwd slashes).
    let lua_abs = std::path::absolute(run_dir.join("dissectors").join("link.lua"))
        .context("absolutize lua path")?
        .to_string_lossy()
        .replace('\\', "/");
    let visualether = format!(
        "# Generated by helixsim — VisualEther MCP tools pick this up automatically.\n\
         \n\
         [defaults]\n\
         tshark-arg = [\n    \"-X\", \"lua_script:{lua_abs}\",\n]\n\
         \n\
         [generate]\n\
         output = \"output/\"\n"
    );
    std::fs::write(run_dir.join("visualether.toml"), visualether)
        .context("write visualether.toml")?;

    let snapshot = Snapshot {
        helixsim_version: env!("CARGO_PKG_VERSION"),
        trace_sha256: &loaded.trace_sha256,
        scenario: &loaded.file,
    };
    std::fs::write(
        run_dir.join("scenario.snapshot.toml"),
        toml::to_string_pretty(&snapshot).context("serialize snapshot")?,
    )
    .context("write snapshot")?;
    Ok(())
}
